### ISSUE TITLE
Feature: Store downloaded log inside `TERMINUS_HOME`

### ISSUE THREAD

**Issue by marfillaster** [geraldvillorente/terminus-logs#2]
By default, downloaded logs are stored in `[PWD/TERMINUS_LOGS_DIR]/site-name/site-env`.

Change default store to `TERMINUS_HOME/cache/terminus-logs/site-name.site-env`.
Use `TERMINUS_LOGS_PREFIX` to serve as override to default store.

**Comment by geraldvillorente** [comment]
This issue is now fixed.
